language: python
python:
    - "2.7"
    - "3.6"
services:
    - postgresql
# install dependancies
install:
    - cd API
    - source travis-env.sh
    - pip install -r requirements.txt
before_script:
    - psql -c 'create database book_a_meal_test;' -U postgres
    - psql -c "create user foo with password 'bar';" -U postgres
# run tests
script:
    - nosetests --with-coverage --cover-package app
# run coverage tests
after_success: 
    - coveralls
