export FLASK_APP="run.py"
export APP_MODE="dev"
export SECRET="232adfadk32323jkadfo23i232323"
export DEFAULT_ADMIN_USERNAME="admin"
export DEFAULT_ADMIN_EMAIL="admin@bam.com"
export DEFAULT_ADMIN_PASSWORD="super-secret"
export JWT_SECRET_KEY="23adfaosdufaosdjfo2jrkjadofjadsf"
export TEST_DATABASE_URL="postgresql://foo:bar@localhost/book_a_meal_test"
